### ISSUE TITLE
Is it possible to run this tool on Linux platform like Ubuntu(ARM64)?

### ISSUE THREAD

**Issue by zhongpengqun** [aquacropos/aquacrop#165]
tmp.py ↓, it is copied from this project's document

```python
from aquacrop import AquaCropModel, Soil, Crop, InitialWaterContent
from aquacrop.utils import prepare_weather, get_filepath

weather_file_path = get_filepath('tunis_climate.txt')
model_os = AquaCropModel(
            sim_start_time=f"{1979}/10/01",
            sim_end_time=f"{1985}/05/30",
            weather_df=prepare_weather(weather_file_path),
            soil=Soil(soil_type='SandyLoam'),
            crop=Crop('Wheat', planting_date='10/01'),
            initial_water_content=InitialWaterContent(value=['FC']),
        )
model_os.run_model(till_termination=True)
model_results = model_os.get_simulation_results().head()
print(model_results)
```
But failed to run it, ↓
```
# python tmp.py 
 Compiling modules... This could take some time.
 Note: The compilation is only necessary the first time that the library is used.
 40%|██████████████████████████████████████████▊                                                                | 8/20 [02:37<03:40, 18.34s/it]Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/aquacrop/solution/HIadj_post_anthesis.py", line 140, in <module>
    cc.compile()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/cc.py", line 221, in compile
    objects, dll_exports = self._compile_object_files(build_dir)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/cc.py", line 209, in _compile_object_files
    compiler.write_native_object(temp_obj, wrap=True)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/compiler.py", line 207, in write_native_object
    library = self._cull_exports()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/compiler.py", line 159, in _cull_exports
    cres = compile_extra(self.typing_context, self.context,
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 744, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 438, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 506, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 481, in _compile_core
    raise e
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 472, in _compile_core
    pm.run(self.state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 364, in run
    raise e
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/typed_passes.py", line 468, in run_pass
    lower.lower()
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 187, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 222, in lower_normal_function
    self.setup_function(fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 297, in setup_function
    self.function = self.context.declare_function(self.module, fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/base.py", line 413, in declare_function
    fnty = self.call_conv.get_function_type(fndesc.restype, fndesc.argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/callconv.py", line 805, in get_function_type
    arginfo = self._get_arg_packer(argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/callconv.py", line 165, in _get_arg_packer
    return self.context.get_arg_packer(argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/base.py", line 320, in get_arg_packer
    return datamodel.ArgPacker(self.data_model_manager, fe_args)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/packer.py", line 81, in __init__
    dm = self._dmm.lookup(ty)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/manager.py", line 37, in lookup
    model = self._cache[fetype] = handler(self, fetype)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 742, in __init__
    super(TupleModel, self).__init__(dmm, fe_type, members)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 524, in __init__
    self._models = tuple([self._dmm.lookup(t) for t in self._members])
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 524, in <listcomp>
    self._models = tuple([self._dmm.lookup(t) for t in self._members])
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/manager.py", line 36, in lookup
    handler = self._handlers[type(fetype)]
KeyError: <class 'type'>
 75%|███████████████████████████████████████████████████████████████████████████████▌                          | 15/20 [04:41<01:45, 21.10s/it]Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/aquacrop/solution/root_development.py", line 278, in <module>
    cc.compile()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/cc.py", line 221, in compile
    objects, dll_exports = self._compile_object_files(build_dir)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/cc.py", line 209, in _compile_object_files
    compiler.write_native_object(temp_obj, wrap=True)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/compiler.py", line 207, in write_native_object
    library = self._cull_exports()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/compiler.py", line 159, in _cull_exports
    cres = compile_extra(self.typing_context, self.context,
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 744, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 438, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 506, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 481, in _compile_core
    raise e
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 472, in _compile_core
    pm.run(self.state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 364, in run
    raise e
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/typed_passes.py", line 468, in run_pass
    lower.lower()
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 187, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 222, in lower_normal_function
    self.setup_function(fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 297, in setup_function
    self.function = self.context.declare_function(self.module, fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/base.py", line 413, in declare_function
    fnty = self.call_conv.get_function_type(fndesc.restype, fndesc.argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/callconv.py", line 805, in get_function_type
    arginfo = self._get_arg_packer(argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/callconv.py", line 165, in _get_arg_packer
    return self.context.get_arg_packer(argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/base.py", line 320, in get_arg_packer
    return datamodel.ArgPacker(self.data_model_manager, fe_args)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/packer.py", line 81, in __init__
    dm = self._dmm.lookup(ty)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/manager.py", line 37, in lookup
    model = self._cache[fetype] = handler(self, fetype)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 742, in __init__
    super(TupleModel, self).__init__(dmm, fe_type, members)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 524, in __init__
    self._models = tuple([self._dmm.lookup(t) for t in self._members])
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 524, in <listcomp>
    self._models = tuple([self._dmm.lookup(t) for t in self._members])
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/manager.py", line 36, in lookup
    handler = self._handlers[type(fetype)]
KeyError: <class 'type'>
 85%|██████████████████████████████████████████████████████████████████████████████████████████                | 17/20 [05:16<00:58, 19.52s/it]Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/aquacrop/solution/HIref_current_day.py", line 166, in <module>
    cc.compile()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/cc.py", line 221, in compile
    objects, dll_exports = self._compile_object_files(build_dir)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/cc.py", line 209, in _compile_object_files
    compiler.write_native_object(temp_obj, wrap=True)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/compiler.py", line 207, in write_native_object
    library = self._cull_exports()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/compiler.py", line 159, in _cull_exports
    cres = compile_extra(self.typing_context, self.context,
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 744, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 438, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 506, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 481, in _compile_core
    raise e
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 472, in _compile_core
    pm.run(self.state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 364, in run
    raise e
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/typed_passes.py", line 468, in run_pass
    lower.lower()
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 187, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 222, in lower_normal_function
    self.setup_function(fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 297, in setup_function
    self.function = self.context.declare_function(self.module, fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/base.py", line 413, in declare_function
    fnty = self.call_conv.get_function_type(fndesc.restype, fndesc.argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/callconv.py", line 805, in get_function_type
    arginfo = self._get_arg_packer(argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/callconv.py", line 165, in _get_arg_packer
    return self.context.get_arg_packer(argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/base.py", line 320, in get_arg_packer
    return datamodel.ArgPacker(self.data_model_manager, fe_args)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/packer.py", line 81, in __init__
    dm = self._dmm.lookup(ty)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/manager.py", line 37, in lookup
    model = self._cache[fetype] = handler(self, fetype)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 742, in __init__
    super(TupleModel, self).__init__(dmm, fe_type, members)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 524, in __init__
    self._models = tuple([self._dmm.lookup(t) for t in self._members])
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 524, in <listcomp>
    self._models = tuple([self._dmm.lookup(t) for t in self._members])
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/manager.py", line 36, in lookup
    handler = self._handlers[type(fetype)]
KeyError: <class 'type'>
 90%|███████████████████████████████████████████████████████████████████████████████████████████████▍          | 18/20 [05:20<00:29, 14.81s/it]Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/aquacrop/solution/temperature_stress.py", line 101, in <module>
    cc.compile()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/cc.py", line 221, in compile
    objects, dll_exports = self._compile_object_files(build_dir)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/cc.py", line 209, in _compile_object_files
    compiler.write_native_object(temp_obj, wrap=True)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/compiler.py", line 207, in write_native_object
    library = self._cull_exports()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/compiler.py", line 159, in _cull_exports
    cres = compile_extra(self.typing_context, self.context,
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 744, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 438, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 506, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 481, in _compile_core
    raise e
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 472, in _compile_core
    pm.run(self.state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 364, in run
    raise e
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/typed_passes.py", line 468, in run_pass
    lower.lower()
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 187, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 222, in lower_normal_function
    self.setup_function(fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 297, in setup_function
    self.function = self.context.declare_function(self.module, fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/base.py", line 413, in declare_function
    fnty = self.call_conv.get_function_type(fndesc.restype, fndesc.argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/callconv.py", line 805, in get_function_type
    arginfo = self._get_arg_packer(argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/callconv.py", line 165, in _get_arg_packer
    return self.context.get_arg_packer(argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/base.py", line 320, in get_arg_packer
    return datamodel.ArgPacker(self.data_model_manager, fe_args)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/packer.py", line 81, in __init__
    dm = self._dmm.lookup(ty)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/manager.py", line 37, in lookup
    model = self._cache[fetype] = handler(self, fetype)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 742, in __init__
    super(TupleModel, self).__init__(dmm, fe_type, members)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 524, in __init__
    self._models = tuple([self._dmm.lookup(t) for t in self._members])
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 524, in <listcomp>
    self._models = tuple([self._dmm.lookup(t) for t in self._members])
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/manager.py", line 36, in lookup
    handler = self._handlers[type(fetype)]
KeyError: <class 'type'>
 95%|████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 19/20 [05:23<00:11, 11.34s/it]Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/aquacrop/solution/biomass_accumulation.py", line 116, in <module>
    cc.compile()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/cc.py", line 221, in compile
    objects, dll_exports = self._compile_object_files(build_dir)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/cc.py", line 209, in _compile_object_files
    compiler.write_native_object(temp_obj, wrap=True)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/compiler.py", line 207, in write_native_object
    library = self._cull_exports()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/pycc/compiler.py", line 159, in _cull_exports
    cres = compile_extra(self.typing_context, self.context,
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 744, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 438, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 506, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 481, in _compile_core
    raise e
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 472, in _compile_core
    pm.run(self.state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 364, in run
    raise e
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/usr/local/lib/python3.9/site-packages/numba/core/typed_passes.py", line 468, in run_pass
    lower.lower()
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 187, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 222, in lower_normal_function
    self.setup_function(fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/lowering.py", line 297, in setup_function
    self.function = self.context.declare_function(self.module, fndesc)
  File "/usr/local/lib/python3.9/site-packages/numba/core/base.py", line 413, in declare_function
    fnty = self.call_conv.get_function_type(fndesc.restype, fndesc.argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/callconv.py", line 805, in get_function_type
    arginfo = self._get_arg_packer(argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/callconv.py", line 165, in _get_arg_packer
    return self.context.get_arg_packer(argtypes)
  File "/usr/local/lib/python3.9/site-packages/numba/core/base.py", line 320, in get_arg_packer
    return datamodel.ArgPacker(self.data_model_manager, fe_args)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/packer.py", line 81, in __init__
    dm = self._dmm.lookup(ty)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/manager.py", line 37, in lookup
    model = self._cache[fetype] = handler(self, fetype)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 742, in __init__
    super(TupleModel, self).__init__(dmm, fe_type, members)
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 524, in __init__
    self._models = tuple([self._dmm.lookup(t) for t in self._members])
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/models.py", line 524, in <listcomp>
    self._models = tuple([self._dmm.lookup(t) for t in self._members])
  File "/usr/local/lib/python3.9/site-packages/numba/core/datamodel/manager.py", line 36, in lookup
    handler = self._handlers[type(fetype)]
KeyError: <class 'type'>
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [05:26<00:00, 16.34s/it]
Traceback (most recent call last):
  File "/api-aquacrop-irr/tmp.py", line 1, in <module>
    from aquacrop import AquaCropModel, Soil, Crop, InitialWaterContent
  File "/usr/local/lib/python3.9/site-packages/aquacrop/__init__.py", line 3, in <module>
    from .core import AquaCropModel
  File "/usr/local/lib/python3.9/site-packages/aquacrop/core.py", line 49, in <module>
    from .timestep.run_single_timestep import solution_single_time_step
  File "/usr/local/lib/python3.9/site-packages/aquacrop/timestep/run_single_timestep.py", line 19, in <module>
    from ..solution.harvest_index import harvest_index
  File "/usr/local/lib/python3.9/site-packages/aquacrop/solution/harvest_index.py", line 21, in <module>
    from .solution_temperature_stress import temperature_stress
ModuleNotFoundError: No module named 'aquacrop.solution.solution_temperature_stress'
```
My OS is Linux, and CPU is ARM64
```
# uname
Linux
# uname -m
aarch64
r# uname -r
5.4.0-1028-raspi
```

**Comment by NickAlexander18** [comment]
Same condition happened in Windows. See the [https://github.com/aquacropos/aquacrop/issues/163](url). The problem is the numba compilation.

I recommand the older version 2.2.3 on the PyPi. Use **pip install aquacrop==2.2.3**
Meanwhile, use **numba <=0.56** and **numpy <=1.22** to avoid the **Import Error**

**Comment by tfoster88** [comment]
Further to @NickAlexander18 helpful comment, this is due to issues with the numba compilation. We are looking into this at the moment and will likely look at removing or significantly changing how the compilation is used and implemented in the next upcoming release. This may take a few weeks though due to our other commitments. 

In the meantime, if you receive an error message such as "No module named..." or "ModuleNotFoundError: No module named... ", please try the following troubleshooting steps:

First, run "python -m aquacrop.scripts.initiate_library" in your terminal, if this generates an error such as "RuntimeError: Attempted to compile AOT function without the compiler used by numpy.distutils present. Cannot find suitable msvc.", then you need to download and install an MSVC compiler such as the one included in Visual Studio build tools (see e.g. https://www.youtube.com/watch?v=p_R3tXSq0KI).

If this doesn't help solve the error message, then you can run aquacrop in pure python using:

import os

os.environ['DEVELOPMENT'] = 'DEVELOPMENT'

This second fix will make the model slower as it turns off the ahead of time compiling which is the common cause of these kinds of error messages

**Comment by zhongpengqun** [comment]
Thanks so much!  @NickAlexander18 @tfoster88 
I did as your answers suggested and solved the issue.
![image](https://github.com/user-attachments/assets/fddd16f8-6501-4d64-ac44-bc4918a9b8d7)
