### ISSUE TITLE
importerror (outdated PyPi?)

### ISSUE THREAD

**Issue by feefladder** [aquacropos/aquacrop#51]
# steps to reproduce:
```python
virtualenv venv
source venv/bin/activate
pip install aquacrop
python
>>> from aquacrop import AquaCropModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'AquaCropModel' from 'aquacrop' (/media/fee/data/Git/aquacrop-xs/venv/lib/python3.10/site-packages/aquacrop/__init__.py)
>>> from aquacrop.core import AquaCropModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/fee/data/Git/aquacrop-xs/venv/lib/python3.10/site-packages/aquacrop/core.py", line 12, in <module>
    from .timestep import *
  File "/media/fee/data/Git/aquacrop-xs/venv/lib/python3.10/site-packages/aquacrop/timestep.py", line 4, in <module>
    from .solution import *
  File "/media/fee/data/Git/aquacrop-xs/venv/lib/python3.10/site-packages/aquacrop/solution.py", line 44, in <module>
    from .solution_aot import (
ModuleNotFoundError: No module named 'aquacrop.solution_aot'
```
However, if I clone the repo and install from there, it works:
```python
virtualenv venv
source venv/bin/activate
pip install git+https://github.com/aquacropos/aquacrop@master
python
>>> from aquacrop import AquaCropModel
 Compiling modules... This could take some time.
 Note: The compilation is only necessary the first time that the library is used.
```
I think this has to do with the PyPi being outdated?

**Comment by thomasdkelly** [comment]
Hi yes I have just merged a big update commit and will be creating the new release (and hence the new pypi version) in a few mins

**Comment by buwenliu** [comment]
I had the same problem when using Aquacrop-Gym, which I downloaded locally with aquacrop==1.1.2.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], [line 3](vscode-notebook-cell:?execution_count=3&line=3)
      [1](vscode-notebook-cell:?execution_count=3&line=1) # import aquacrop functions (the * simply means 'all')
      [2](vscode-notebook-cell:?execution_count=3&line=2) from aquacrop.classes import    *
----> [3](vscode-notebook-cell:?execution_count=3&line=3) from aquacrop.core import       *

File [c:\Users\13166\anaconda3\envs\gymaquacrop\lib\site-packages\aquacrop\core.py:12](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/core.py:12)
     [10](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/core.py:10) # Cell
     [11](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/core.py:11) from .initialize import *
---> [12](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/core.py:12) from .timestep import *
     [13](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/core.py:13) from .classes import *
     [14](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/core.py:14) from aquacrop import data

File [c:\Users\13166\anaconda3\envs\gymaquacrop\lib\site-packages\aquacrop\timestep.py:4](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/timestep.py:4)
      [1](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/timestep.py:1) __all__ = ["solution", "check_model_termination", "reset_initial_conditions", "update_time"]
      [3](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/timestep.py:3) # Cell
----> [4](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/timestep.py:4) from .solution import *
      [5](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/timestep.py:5) from .initialize import calculate_HI_linear, calculate_HIGC
      [6](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/timestep.py:6) from .classes import *

File [c:\Users\13166\anaconda3\envs\gymaquacrop\lib\site-packages\aquacrop\solution.py:44](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/solution.py:44)
     [42](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/solution.py:42) # This compiled function is called a few times inside other functions
     [43](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/solution.py:43) if __name__ != "__main__":
---> [44](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/solution.py:44)     from .solution_aot import (
...
     [60](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/solution.py:60) # @njit()
     [61](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/solution.py:61) @cc.export("_growing_degree_day", "f8(i4,f8,f8,f8,f8)")
     [62](file:///C:/Users/13166/anaconda3/envs/gymaquacrop/lib/site-packages/aquacrop/solution.py:62) def growing_degree_day(GDDmethod, Tupp, Tbase, Tmax, Tmin):

ModuleNotFoundError: No module named 'aquacrop.solution_aot'

Want to ask how to solve?
